# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "CAT" ("name" VARCHAR NOT NULL PRIMARY KEY,"color" VARCHAR NOT NULL);
create table "TranslateFile" ("inPath" VARCHAR NOT NULL,"translatedText" VARCHAR NOT NULL,"editMode" VARCHAR NOT NULL,"deleted" BOOLEAN NOT NULL,"isRequired" BOOLEAN NOT NULL,"isVerified" BOOLEAN NOT NULL,"outPath" VARCHAR,"id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY);

# --- !Downs

drop table "CAT";
drop table "TranslateFile";

